### ISSUE TITLE
Folder icons are not present for embedded workspaces for the workspace file listing

### ISSUE THREAD

**Issue by jonrkarr** [PMR2/pmr2.app#8]
Example: https://models.physiomeproject.org/workspace/705/@@file/a3428d102cec10f55c51c13731a78e812f9bab04/
- `GPCR_B1AR_reduced`
- `GPCR_M2_reduced`
- `cAMP`
- `units_and_constants`

**Comment by metatoaster** [comment]
These are not folders but are embedded workspaces, which are links to other git repositories which may be other workspaces.

Yes this is a known issue.

**Comment by jonrkarr** [comment]
In that case, ideally the icon would indicate a Git submodule.

**Comment by metatoaster** [comment]
Agreed. This was implemented back with the Mercurial based workspaces, but for some reason this broke in Git but nobody seemed to care, but yes this should be fixed.

**Comment by metatoaster** [comment]
Deployed to production.
