### ISSUE TITLE
Provide link to report issues with exposures

### ISSUE THREAD

**Issue by metatoaster** [PMR2/pmr2.app#9]
Given that [the issue tracker at this GitHub repository](https://github.com/PMR2/models.physiomeproject.org/issues) is being used to track issues to do with models in PMR, it would be good to provide a link from the exposure to a prefilled template to file the relevant issue they may have found.

**Comment by metatoaster** [comment]
This feature has been created and deployed onto the staging instance.

- The version for workspace is currently listed immediately above the list of files in the main page, under the heading "Report an issue with this workspace" ([workspace](https://staging.physiomeproject.org/workspace/beeler_reuter_1977))
- The version for exposure is linked from tools, under the heading "Report an issue with this exposure" ([exposure](https://staging.physiomeproject.org/e/c1/) [file](https://staging.physiomeproject.org/e/c1/beeler_reuter_1977.cellml/view))

Please feel free to have a play with it as is, people who have interacted significantly or have filed a large number of issues may be interested in providing a comment or opinion about this feature, such as the wording of the link and associated form on the issue tracker.

cc: @nickerso @bilalshaikh42 @MichaelClerx @jonrkarr

**Comment by MichaelClerx** [comment]
Thanks @metatoaster !
It looks good, but you might want to change the automatically set title for exposure issues? The URI already contains the exact exposure, so this could perhaps be something less scary like `Problem with Beeler, Reuter, 1977` (workspace name), or `Problem with "Reconstruction of the action potential of ventricular myocardial fibres"` (exposure name).

Similarly, I suspect the `Report an issue with this exposure` button will go untouched by most users, who are blissfully unaware of what an exposure is. (Semantically it doesn't make sense either, you wouldn't report an issue with a git tag, but an issue with the stuff stored at the commit that the tag references). This could just be "Report a problem with this model", I think. (Sure, an exposure can technically expose something other than a model, but unless we're also renaming it the Physiome Exposure Repository I feel "model" should be general enough in this case)

**Comment by metatoaster** [comment]
Modified the wording to "resource" to be even more generic to work around the "other than a model" issue, and it is now staged, along with the title change.

**Comment by metatoaster** [comment]
This was released yesterday onto production.
